project.description="Extra support for Kotlin Multiplatform"
project.group=org.danbrough
#
publish.local=true
publish.sonatype=true
publish.xtras=true
publish.docs=1
publish.sign=1
#
#sonatype.baseURL=https://s01.oss.sonatype.org
org.gradle.daemon=true
org.gradle.jvmargs=-XX\:MaxMetaspaceSize\=2G -Xmx2048m -Xss32m
#org.gradle.caching=true
org.gradle.configuration-cache=false
#org.gradle.unsafe.configuration-cache=true
#Android
#android.disableAutomaticComponentCreation=true
android.useAndroidX=true
android.enableJetifier=true
#Kotlin
kotlin.code.style=official
#kotlin.mpp.enableCInteropCommonization=true
#kotlin.native.binary.memoryModel=experimental
kotlin.native.ignoreDisabledTargets=true
#kotlin.mpp.stability.nowarn=true
kotlin.mpp.applyDefaultHierarchyTemplate=true
#kotlin.mpp.androidGradlePluginCompatibility.nowarn=true
#kotlin.mpp.enableCInteropCommonization.nowarn=true
kotlin.mpp.enableCInteropCommonization=true
#org.jetbrains.dokka.experimental.gradle.pluginMode=V2EnabledWithHelpers
org.jetbrains.dokka.experimental.gradle.pluginMode=V2Enabled
org.jetbrains.dokka.experimental.gradle.pluginMode.noWarn=true
#xtras2.message=Hello World! from gradle.properties
#
#sodium library default settings
sodium.version=1.0.20
sodium.git.commit=1.0.20-RELEASE
sodium.git.url=https://github.com/jedisct1/libsodium
#
#zmq library default settings
zmq.version=4.3.5
zmq.git.commit=v4.3.5
zmq.git.url=https://github.com/zeromq/libzmq.git
#
#
#openssl library default settings
openssl.version=3.6.1
openssl.git.commit=e4eed62a477c3adb986b001fbd7a098f31607518
openssl.git.url=https://github.com/openssl/openssl
#
sqlite.version=3.51.2
sqlite.git.commit=ba76c160c735437de974c6ea24c890a663214c6b
sqlite.git.url=https://github.com/sqlite/sqlite
xtras.description=Xtras Description
#
#curl library settings
curl.version=8.18.0
curl.git.url=https://github.com/curl/curl.git
curl.git.commit=77e260ec0ea1dd9a30197b60773d42f19ff19005
