# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: publish

on:
  workflow_dispatch:
  #workflow_call:


#  release:
#    types: [ created ]

jobs:
  setup:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          #cache: gradle

      - uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r26d
          add-to-path: true
        env:
          ANDROID_NDK: ${{ steps.setup-ndk.outputs.ndk-path }}

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Set up Android SDK
        if: ${{ env.ACT }} # Only run on local act setups, as GitHub Actions provides the Android SDK on Ubuntu
        uses: android-actions/setup-android@v3.2.1

      - name: Setup gradle.properties
        shell: bash
        run: |
          echo XTRAS_DIR=$HOME/xtras >> $GITHUB_ENV
          GRADLE_PROPS=$HOME/.gradle/gradle.properties
          echo Configuring $GRADLE_PROPS 
          if [ -f $GRADLE_PROPS ]; then
            echo existing $GRADLE_PROPS
            cat $GRADLE_PROPS
          fi
          cat > $GRADLE_PROPS <<PROPS
          org.gradle.caching=true
          signing.key=${{ secrets.GPG_SIGNING_KEY }}
          signing.password=${{ secrets.GPG_SIGNING_PASSWORD }}
          sonatype.profileID=${{ secrets.SONATYPE_PROFILE_ID }}
          sonatype.username=${{ secrets.SONATYPE_USERNAME }}
          sonatype.password=${{ secrets.SONATYPE_PASSWORD }}
          xtras.dir=$HOME/xtras
          PROPS
          chmod 600 $GRADLE_PROPS

      - name: Cache Xtras dir
        id: cache_xtras
        uses: actions/cache@v4.0.2
        with:
          path: ${{ env.XTRAS_DIR }}
          key: ${{ runner.os }}-xtras

      - name: Upgrade
        #if: ${{ env.ACT }} # Only run on local act setups, as GitHub Actions provides the Android SDK on Ubuntu
        shell: bash
        run: |
          #sudo apt -qq update
          #sudo apt -qq -y upgrade
          sudo apt -qq install cmake libssl-dev build-essential libffi-dev curl libz-dev ninja-build 

      - name: publish_plugin
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          ./gradlew :plugin:publishAllPublicationsToSonatypeRepository -PpluginOnly=1 \
          -Psonatype.closeRepository=1 

      - name: publish_libs
        env:
          USERNAME: ${{ github.actor }}
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        run: |
          ./gradlew xtrasPackageCreateDuckdbLinuxX64 


#          ./gradlew :core:publishAllPublicationsToSonatypeRepository \
#          -Pxtras.dir=$HOME/xtras -Ppublish.docs=1 -Ppublish.sign=1 \
#          -Psigning.key="${{ secrets.GPG_SIGNING_KEY }}" \
#          -Psigning.password="${{ secrets.GPG_SIGNING_PASSWORD }}" \
#          -Psonatype.profileID=${{ secrets.SONATYPE_PROFILE_ID }} \
#          -Psonatype.username=${{ secrets.SONATYPE_USERNAME }} \
#          -Psonatype.password="${{ secrets.SONATYPE_PASSWORD }}"
#
#          ./gradlew :support:publishAllPublicationsToSonatypeRepository \
#          -Pxtras.dir=$HOME/xtras -Ppublish.docs=1 -Ppublish.sign=1 \
#          -Psigning.key="${{ secrets.GPG_SIGNING_KEY }}" \
#          -Psigning.password="${{ secrets.GPG_SIGNING_PASSWORD }}" \
#          -Psonatype.profileID=${{ secrets.SONATYPE_PROFILE_ID }} \
#          -Psonatype.username=${{ secrets.SONATYPE_USERNAME }} \
#          -Psonatype.password="${{ secrets.SONATYPE_PASSWORD }}"


#      - name: Publish Libs
#        env:
#          #          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
#          #          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
#          USERNAME: ${{ github.actor }}
#          TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        shell: bash
#        run: |
#          ./gradlew publishAllPublicationsToSonatypeRepository \
#          -Ppublish.docs=1 -Ppublish.sign=1 \
#          -Pxtras.dir=$HOME/xtras \
#          -Psigning.key="${{ secrets.GPG_SIGNING_KEY }}" \
#          -Psigning.password="${{ secrets.GPG_SIGNING_PASSWORD }}" \
#          -Psonatype.username=${{ secrets.SONATYPE_USERNAME }} \
#          -Psonatype.password="${{ secrets.SONATYPE_PASSWORD }}"
#

