# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a package using Gradle and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#Publishing-using-gradle

name: Publish

on: workflow_dispatch
#  release:
#    types: [ created ]

jobs:
  uses: danbrough/xtras/.github/workflows/setup.yml@5528d3467d8848ddefd535d12eeef8283ccf7f82

  build_plugin:
    permissions:
      contents: read
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: fred
        uses: danbrough/xtras/.github/workflows/setup.yml@5528d3467d8848ddefd535d12eeef8283ccf7f82
        shell: bash
        run: |
          ./gradlew :plugin:publishAllPublicationsToSonatypeRepository -PpluginOnly=1 \
          -Pxtras.dir=$HOME/xtras -Ppublish.docs=1 -Ppublish.sign=1 -Psonatype.closeRepository=1 \
          -Psigning.key="${{ secrets.GPG_SIGNING_KEY }}" \
          -Psigning.password="${{ secrets.GPG_SIGNING_PASSWORD }}" \
          -Psonatype.profileID=${{ secrets.SONATYPE_PROFILE_ID }} \
          -Psonatype.username=${{ secrets.SONATYPE_USERNAME }} \
          -Psonatype.password="${{ secrets.SONATYPE_PASSWORD }}"




#    steps:
#      shell: bash
#      run: ls /
#
#  build_plugin:
#    steps:
#    -name: build_plugin
#        shell: bash
#        run: |
#          ./gradlew :plugin:publishAllPublicationsToSonatypeRepository -PpluginOnly=1 \
#          -Pxtras.dir=$HOME/xtras -Ppublish.docs=1 -Ppublish.sign=1 -Psonatype.closeRepository=1 \
#          -Psigning.key="${{ secrets.GPG_SIGNING_KEY }}" \
#          -Psigning.password="${{ secrets.GPG_SIGNING_PASSWORD }}" \
#          -Psonatype.profileID=${{ secrets.SONATYPE_PROFILE_ID }} \
#          -Psonatype.username=${{ secrets.SONATYPE_USERNAME }} \
#          -Psonatype.password="${{ secrets.SONATYPE_PASSWORD }}"

#          ./gradlew :core:publishAllPublicationsToSonatypeRepository \
#          -Pxtras.dir=$HOME/xtras -Ppublish.docs=1 -Ppublish.sign=1 \
#          -Psigning.key="${{ secrets.GPG_SIGNING_KEY }}" \
#          -Psigning.password="${{ secrets.GPG_SIGNING_PASSWORD }}" \
#          -Psonatype.profileID=${{ secrets.SONATYPE_PROFILE_ID }} \
#          -Psonatype.username=${{ secrets.SONATYPE_USERNAME }} \
#          -Psonatype.password="${{ secrets.SONATYPE_PASSWORD }}"
#
#          ./gradlew :support:publishAllPublicationsToSonatypeRepository \
#          -Pxtras.dir=$HOME/xtras -Ppublish.docs=1 -Ppublish.sign=1 \
#          -Psigning.key="${{ secrets.GPG_SIGNING_KEY }}" \
#          -Psigning.password="${{ secrets.GPG_SIGNING_PASSWORD }}" \
#          -Psonatype.profileID=${{ secrets.SONATYPE_PROFILE_ID }} \
#          -Psonatype.username=${{ secrets.SONATYPE_USERNAME }} \
#          -Psonatype.password="${{ secrets.SONATYPE_PASSWORD }}"


#      - name: Publish Libs
#        env:
#          #          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}
#          #          GPG_SIGNING_PASSWORD: ${{ secrets.GPG_SIGNING_PASSWORD }}
#          USERNAME: ${{ github.actor }}
#          TOKEN: ${{ secrets.GITHUB_TOKEN }}
#        shell: bash
#        run: |
#          ./gradlew publishAllPublicationsToSonatypeRepository \
#          -Ppublish.docs=1 -Ppublish.sign=1 \
#          -Pxtras.dir=$HOME/xtras \
#          -Psigning.key="${{ secrets.GPG_SIGNING_KEY }}" \
#          -Psigning.password="${{ secrets.GPG_SIGNING_PASSWORD }}" \
#          -Psonatype.username=${{ secrets.SONATYPE_USERNAME }} \
#          -Psonatype.password="${{ secrets.SONATYPE_PASSWORD }}"
#

